### DOCKER_IMAGE ###############################################################

DOCKER_IMAGE_TAG	?= edge
OS_RELEASE		?= 3.12

### IMAGE_MK ###################################################################

BUILD_DIR		?= $(abspath $(CURDIR)/..)
PROJECT_DIR		?= $(abspath $(BUILD_DIR)/..)

include $(BUILD_DIR)/image.mk

################################################################################
