### DOCKER_IMAGE ###############################################################

DOCKER_IMAGE_TAG	?= 3.11
DOCKER_IMAGE_TAGS	?= 3 latest

### IMAGE_MK ###################################################################

BUILD_DIR		?= $(abspath $(CURDIR)/..)
PROJECT_DIR		?= $(abspath $(BUILD_DIR)/..)

include $(BUILD_DIR)/image.mk

################################################################################
