name: Build and Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Checkout Mk
        run:  git clone https://github.com/iBossOrg/Mk ../Mk

      - name: Login to Docker registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull images
        run: make pull
        continue-on-error: true

      - name: Build and test images
        run:  make images
        env: { RSPEC_FORMAT: doc }

      - name: Publish images
        run:  make publish
